version: "3"
services:
  web-nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: web-server
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
