version: "3"
services:
  web-client:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-ui
    stdin_open: true
    volumes:
      - .:/app
      - /node_modules
    networks: [webappnetwork]

  web-nginx:
    image: nginx:alpine
    container_name: web-server
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-client
    ports:
      - "3000:80"
    networks: [webappnetwork]

networks:
  webappnetwork:
    driver: bridge
